import { Fredoka, Italianno } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/Components/Shared/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/Components/Shared/Footer";


const fredoka = Fredoka({
  subsets: ["latin"],
});
export const italianno = Italianno({
  subsets: ["latin"],
  weight: '400',
});



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${fredoka.className}  h-full antialiased`}
    >
      <body className="min-h-full  flex flex-col">
        <main className="">{children}</main>
      </body>
    </html>
  );
}
