import { Fredoka,Italianno } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/Components/Shared/Navbar";


const fredoka = Fredoka({
  subsets: ["latin"],
});
export const italianno = Italianno({
  subsets: ["latin"],
   weight: '400',
});



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${fredoka.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        <main className=" grow">{children}</main>

      </body>
    </html>
  );
}
