import { Fredoka, Italianno } from "next/font/google";
import "./globals.css";

import { Toaster } from "react-hot-toast";
import DeshBoardPage from "./deshboard/page";
import Sidebar from "@/Components/Sidebar/Sidebar";
import SidebarNav from "@/Components/Sidebar/SidebarNav";



const fredoka = Fredoka({
  subsets: ["latin"],
});
export const italianno = Italianno({
  subsets: ["latin"],
  weight: '400',
});



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DeshBoardRootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${fredoka.className}  h-full antialiased`}
    >
      <body className="min-h-full  flex flex-col">
        <aside>
          <Sidebar></Sidebar>
        </aside>

        <div className="flex-1 flex-col min-h-screen">

          <div className="flex justify-end bg-black h-20 items-center px-5">
            <SidebarNav></SidebarNav>
          </div>

          <main className=" grow lg:ml-[280px]">{children}</main>
          <Toaster />
        </div>

      </body>
    </html>
  );
}
